### ISSUE TITLE
Add support for Commerce 3

### ISSUE THREAD

**Issue by eirabben** [elleracompany/commerce-klarna-checkout#23]
The plugin does not currently work with Craft Commerce version 3.

**Comment by bitboxth** [comment]
When will we get the support for Craft Commerce version 3? Is being worked on?

**Comment by jellingsen** [comment]
Hi! 

Support for v3 is next in line and should be expected soon.

Sorry for the delay

**Comment by jellingsen** [comment]
The plugin should now be compatible with Commerce 3.
