### ISSUE TITLE
ShipmentAddress falsely becomes same as billingAddress

### ISSUE THREAD

**Issue by jolappi** [elleracompany/commerce-klarna-checkout#33]
Klarna paymentform shows only billing address and not shipment address and 
in this case when KlarnaCheckout.php receives response  from Klarna the shipping address is falsely same as billing address and function updateOrder in KlarnaCheckout.php overwrites already stored shipping address for the order.
We fixed this temporarily so that we won't store shippingaddress at all when we receive response
like so
		if($response->getData()->shipping_address) {
			//$order->setShippingAddress($this->createAddressFromResponse($response->getData()->shipping_address));
			//if($response->getData()->shipping_address->email) $order->setEmail($response->getData()->shipping_address->email);
		}

Better fix would be appreciated

**Comment by jellingsen** [comment]
Hi,

After some investigating i found that Klarna stores the content of billing_address for both addresses in their system. Looking at the logs inside portal.klarna.com its clear that we send billing and shipping addresses with separate content, but when Klarna replies the content of the billing address are populated in both billing and shipping.

Are you seeing the same if you log in to your portal and check some of the Create order log entries?

I have reached out to Klarna support to get some clearity, I will update when they respond.

**Comment by jellingsen** [comment]
Hi,

I have now release v1.1.11. Turns out there is an option in the order to `allow_separate_shipping_address`. This for some reason defaults to false.

I have now added this setting and hard-coded it to true. If this needs to be an option in the settings I will revisit this issue.
