### ISSUE TITLE
Zero delivery discount gives division by zero error

### ISSUE THREAD

**Issue by jolappi** [elleracompany/commerce-klarna-checkout#35]
If one creates discount for delivery costs(zero costs) then in 
KlarnaOrderLine.php line 111 gives Division by zero error when trying to checkout

easy fix to replace line 111 with this
        $this->tax_rate = (int) 0;
        if (($shipping_base_price-$tax_included)!=0){
		    $this->tax_rate = (int) round((($tax_excluded+$tax_included)/($shipping_base_price-$tax_included))*10000);
        }

**Comment by jellingsen** [comment]
Thank you. This is now fixed in v1.1.10.
