### ISSUE TITLE
Different API-keys per site

### ISSUE THREAD

**Issue by eirabben** [elleracompany/commerce-klarna-checkout#41]
We have a project with two sites, Norwegian and Swedish. These sites are set up to use their respective currencies. 

Apparently, Klarna requires a different account with a separate set of API-keys for each currency. Is there any way to do this with the plugin today?

If not, this is a feature request to allow different API-keys per site.

**Comment by jellingsen** [comment]
Hi

You could create two Klarna gateways from the same Gateway class. They credentials are stored on the gateway.

**Comment by eirabben** [comment]
Wow, didn't think of that. Thanks!
