### ISSUE TITLE
Change country per gateway or site

### ISSUE THREAD

**Issue by eirabben** [elleracompany/commerce-klarna-checkout#42]
I am developing a multisite store for Norway and Sweden. It is currently setup with two sites, and two Klarna gateways for the different countries.

It seems that the gateway populates the country that it sends to Klarna from the country in Commerce store location address, so Klarna always receives NO as country. This is rejected when using the swedish gateway. I don't see any way to change the store location address on a per-site basis using aliases or config settings.

Is there any way to solve this? Could we add a setting on the gateway? Could the customer address be used?

**Comment by jellingsen** [comment]
I'll have a look at it!

**Comment by hjelmz** [comment]
Is there anything new in this case?

**Comment by jellingsen** [comment]
I will get to this in the beginning of next week. Sorry for the delay.

**Comment by hjelmz** [comment]
Is something happening? I expect that this will be in place during the day !!

**Comment by jellingsen** [comment]
@hjelmz - It will, I don't work nights ;)

@eirabben - I have made the code changes in a new branch `release/v1.1.14`. I need to do some more testing before I can publish it. Feel free to give it a test in a dev environment.

**Comment by eirabben** [comment]
I tested it, and there seems to be a bug in the country dropdown, where it uses the index in the list instead of the actual ID of the country. I fixed it by changing the code in the `getCountryDropdown` function:

```
// Old
ArrayHelper::map(
  Country::find()->select(['id', 'name'])->all(),
  'id',
  'name'
)

// New
array_map(function($country) {
  return [
    'label' => $country->name,
    'value' => $country->id,
  ];
}, Country::find()->select(['id', 'name'])->all())
```

With this change, everything seems to work.

**Comment by jellingsen** [comment]
You are indeed correct. Craft is expecting an associative array with label and value for dropdowns.

Thank you, good catch.
