### ISSUE TITLE
Payment not working

### ISSUE THREAD

**Issue by wilmer05** [elleracompany/commerce-klarna-checkout#45]
Hello, I just added the last version of the Klarna plugin, but I'm getting the following error:

![Screenshot from 2021-01-18 17-06-52](https://user-images.githubusercontent.com/4504602/104938741-c38eda00-59af-11eb-82f0-ff4f937ba0d4.png)

The problem is on the line 646, the signature of the function maybe should require an object of type stdClass and not object. I tried updating craft but the problem persists

Best regards

**Comment by wilmer05** [comment]
as stated here https://stackoverflow.com/questions/13287593/stdclass-and-type-hinting

The objects in php doesn't have object as class parent of all classes but stdClass

**Comment by jellingsen** [comment]
You are on 7.1 or lower, correct?

The lastest plugin version was developed and tested on PHP 8.0, the Object type was implemented in PHP 7.2.

I'll have a fix for this out by tomorrow.

**Comment by wilmer05** [comment]
My version is 7.4. The server we have is also in this version, Please let me know when the fix is there :) so I can try it again

Thank you

**Comment by jellingsen** [comment]
Try upgrading to v3.0.1 and see if it works for you now.

**Comment by jellingsen** [comment]
Closing this. Please reopen or create a new issue should you still have problems.
