### ISSUE TITLE
Use actionTrigger config setting to generate action URLs

### ISSUE THREAD

**Issue by aelvan** [elleracompany/commerce-klarna-checkout#48]
Both in [HostedForm and CheckoutForm](https://github.com/elleracompany/commerce-klarna-checkout/search?q=actions), the return URL's have `/actions/` hardcoded into them. This makes the payment process fail if the [`actionTrigger` config setting](https://craftcms.com/docs/3.x/config/config-settings.html#actiontrigger) has been customized. 

Hope you can change this to either use the config setting, or (preferably) replacing the whole URL creation with `UrlHelper::actionUrl()` which will deal with this and several other edge-cases automatically (I think `getStoreUrl()` is redundant, unless there's an important cave-at I miss?).

**Comment by jellingsen** [comment]
Thank you. I'll get that sorted out. Should be an easy fix.
