### ISSUE TITLE
after update v3 error 

### ISSUE THREAD

**Issue by cstoerzer** [elleracompany/commerce-klarna-checkout#49]
After update settings gateway settings are not possible:
/admin/commerce/settings/gateways => throws error

Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: ellera\commerce\klarna\gateways\KlarnaCheckout::store_country

Can't access the settings

**Comment by jellingsen** [comment]
Hi,

What version of the plugin are you using? Are you able to recreate that behavior on a fresh install by any chance?

**Comment by cstoerzer** [comment]
Hi,

was after update from last 1.1.14 version. Fresh install works.

I just found a solution wich works for me, but maybe not for someone else. If I delete all customer and order data from craft_commerce tables, than v3 loads without error
