### ISSUE TITLE
Error:  Could not authorize with Klarna

### ISSUE THREAD

**Issue by iamtompickering** [elleracompany/commerce-klarna-checkout#50]
I have just installed it and set it up locally, in test mode with some EU playground credentials, but I am hitting 401 errors.

In the logs it is coming up as:

```
2021-03-15 16:36:43 401 Unauthorized: POST https://api.klarna.com/checkout/v3/orders
2021-03-15 16:37:48 401 Unauthorized: POST https://api.playground.klarna.com/checkout/v3/orders
```

On the front end it just comes up with:
```
Could not authorize with Klarna. Check your credentials.
```

Any help on this would be really appreciated, thanks!

**Comment by jellingsen** [comment]
Hi,

These are the most common reasons for a 401:

- If you signed up for Klarna Payments instead of Klarna Checkout by mistake
- You’re using production credentials on playground or playground credentials on production
- You have a US or OC klarna account
- Trailing whitespaces before or after the password/uid

Based on your description, the first point is probably most likely

**Comment by iamtompickering** [comment]
Hey @jellingsen sorry if this is a dumb question (definitely is!) but how do I find out if my Playground account is Klarna Payments / Checkout?!

**Comment by iamtompickering** [comment]
@jellingsen I've just tried setting up another Playground account from scratch but it doesn't state anywhere whether its a Klarna Payments or Klarna Checkout account. Is this a limitation with the Playground accounts maybe?

**Comment by jellingsen** [comment]
Hi,

No, we're using playground for all our testing as well. That is not the issue.

Could you link the content `storage/logs/klarna-checkout.log` (or `storage/logs/klarna-hpp.log`) and see if there is any clues there?

I'm not sure exactly how the Payments vs. Checkout accounts work, I just know its been an issue in the past.

**Comment by iamtompickering** [comment]
Hey @jellingsen 

So the error that is being logged is the following: 

`2021-03-24 13:19:02 401 Unauthorized: POST https://api.playground.klarna.com/checkout/v3/orders`

**Comment by jellingsen** [comment]
Okey, if you've made sure all the bullet points in my first comment are checked, I think you need to contact Klarna.

I've just installed a fresh craft with commerce and the klarna-plugin, and I had no issues with our playground account.

**Comment by cstoerzer** [comment]
So Klarna Payments does not work with your plugin? Any plans for supporting it in future?

**Comment by jellingsen** [comment]
Yes, we do plan on supporting payments in a future update. 

@iamtompickering  did you get it to work?

**Comment by iamtompickering** [comment]
@jellingsen I didn't have any luck unfortunately, but have just put this on hold for now. My client is signing up for an account for their business. So once they have done this, I will test it all again but running through their account instead.

**Comment by jellingsen** [comment]
I'll close this for now. Should you still have problems, please create a new issue.
