### ISSUE TITLE
Redirect url-issue on multiple site languages

### ISSUE THREAD

**Issue by SandraSundqvist** [elleracompany/commerce-klarna-checkout#62]
Hi, 

We have a site in two different languages. The Url:s for the site looks like this: 
https://domain-name.com/ (English site, main) 
https://domain-name.com/se/ (Swedish site) 

We noticed that the redirect-url to the order complete page, after completing a purchase with Klarna, doesn't take in count the "se" when redirecting. The customer always land on the English/main version, like https://domain-name.com/redirecturl?number=xxxxxxxxxxxx but they should land on https://domain-name.com/se/redirecturl?number=xxxxxxxxxxxx when purchase is made in swedish. 

This seems to be due to a slash('/') that is added first to the redirect-function in the KlarnaController.php on row 103,
`return $this->redirect('/'.$transaction->gateway->success.'?number='.$transaction->order->number);`

Removing the slash solved our issue.

**Comment by jellingsen** [comment]
Hi!

Thank you for reporting this. We'll make adjustments in the next update.
