### ISSUE TITLE
Exception “Division by zero” when line item amount is zero

### ISSUE THREAD

**Issue by SandraSundqvist** [elleracompany/commerce-klarna-checkout#63]
Hi, 

I’ve noticed a problem with discounts. If the amount of a line item in the cart is zero (in our case when a discount is being added that makes one, or several, item(s) free of charge), the tax rate calculation fails and an exception is thrown due to "Division by zero" in the `getTaxRate()`-function in `helpers/TaxExtractor.php` (line 60). 

Exception thrown: 
`PHP Warning 'yii\base\ErrorException' with message 'Division by zero' `

Function failing: 
```
public function getTaxRate() : int
{
      return (int)round(($this->getTaxTotal()/$this->getTotalNet())*10000);
}
```

When the amount of a line item is zero, both the `$this->getTaxTotal()` and `$this->getTotalNet()` are zero, which causes the return-statement to fail. Maybe an if-statement could do the trick here?  Hope this is something you have the time to look into for the next release. Would be very much appreciated!

**Comment by jellingsen** [comment]
Hi!

We've received another report on that as well, and are working on it. The previous reporter is using the current rewrite to make it work;

```
public function getTaxRate() : int
{
    if($this->getTotalNet() === 0) {
      return 0;
    }
    else {
      return (int)round(($this->getTaxTotal()/$this->getTotalNet())*10000);
    }
}"
```

We'll get this out in the next version, within the week.
Thank you for letting us know.

**Comment by SandraSundqvist** [comment]
Super! Thanks! 👍
