### ISSUE TITLE
business name don't return from klarna

### ISSUE THREAD

**Issue by bitboxth** [elleracompany/commerce-klarna-checkout#64]
Hi,

the business name in orders form craft don't return from klarna...

Class: ellera\commerce\klarna\gateways\Base
Methode: createAddressFromResponse(\stdClass $addr)
row: 483-496

businessName reutrn in street_address2
I fixed them temporaly in my use.
$address->businessName = $addr->street_address2;

**Comment by jellingsen** [comment]
I can't seem to find a way to add the business name in the checkout-process, but I should also most certanly be 
`$address->businessName = $addr->orgnaization_name ?? null` right?

I've added the above code, in addition to `$address->address2 = $addr->street_address2 ?? null;`
