### ISSUE TITLE
Response code 500 when trying to access checkout page for an inactive cart

### ISSUE THREAD

**Issue by SandraSundqvist** [elleracompany/commerce-klarna-checkout#67]
Hi, 

We noticed a problem when returning to an inactive cart (on the checkout page as a logged in user) that has Klarna set as gateway. We then get a 500 response from craft due to the Klarna plugin throwing an "InvalidConfigException", with a message of "404:null" in the Klarna-checkout log.

So it seems like the plugin can't find the order in Klarna. These inactive carts have "Authorize" -transactions from Klarna set on them, so maybe the Klarna order referenced in the transactions doesn't exist anymore? If this is the case, would it then be possible to create a new Klarna order instead of throwing an exception? The exception now makes it impossible for a customer to complete the purchase.

**Comment by aelvan** [comment]
Also running into this after trying to upgrade to 3.1.1. I reverted, and the issue is not there on 3.0.3, which leads me to suspect that the issue was introduced when fixing #51 in 3.1.0.

**Comment by jellingsen** [comment]
I will look into this.

Thank you both for detailed explanations and sharing your findings.

**Comment by jellingsen** [comment]
I'm unable to recreate this with the default shop-templates from Craft Commerce.

Could you describe how I could reproduce this?

**Comment by aelvan** [comment]
If I recall correctly, this only happens when trying to perform a checkout if a user has a cart that was created prior to updating to 3.1.1 and that has a transaction entry from Klarna (ie, they visited the checkout page, tried to pay, or something). As @SandraSundqvist writes, it _felt_ like the plugin has a reference to a Klarna order that had expired or something, which lead me to assume that #51 was the culprit since it tries to avoid creating multiple Klarna orders for the same Craft orders. 

So, understandably it could be hard to reproduce. I can try to debug further, but don't have the time right now.

**Comment by jellingsen** [comment]
Ah, that makes sense. Thank you, I'll downgrade, make a few orders and then upgrade.

**Comment by aelvan** [comment]
Yeah, but it might be even harder, because maybe it'll actually work if the Klarna orders were recently created. :)

**Comment by jellingsen** [comment]
Okey, so this might be tricky then. I'll make a few tests and see what I find. 
Maybe the fix in #51 was a bit hasty, but it made sense at the time..

I'll post my findings and suggestions and we'll see how we solve this.

**Comment by SandraSundqvist** [comment]
I can't really say if it started happening after we updated the plugin, but we did an update recently to when we first noticed this problem. So it's very much possible that the issue has got to do with this that you are discussing. 

I don't know if this is a perfect solution, but we did a temporary workaround that seems to be working. In the `authorize()` function (in gateways/Checkout.php) we made a  try catch around the `$form->updateOrder()` (row 85). So if the `updateOrder()` fails, we capture the exception and create a new order in Klarna:

```
public function authorize(Transaction $transaction, BasePaymentForm $form): RequestResponseInterface
    {
        // Check if the received form is of the right type
        if(!$form instanceof CheckoutForm)
            throw new BadRequestHttpException('Klarna Checkout only accepts CheckoutForm');

        if(
            isset($transaction->order->lastTransaction) &&
            strlen($transaction->order->lastTransaction->reference) > 10 &&
            $transaction->order->lastTransaction->type === 'authorize' &&
            $transaction->order->lastTransaction->status === 'pending' &&
            $transaction->order->lastTransaction->gatewayId === $transaction->gatewayId
        ) {
            // This order is already created
            $transaction->note = 'Updated authorized Klarna Order';
            $transaction->parentId = $transaction->order->lastTransaction->message === 'OK' ? $transaction->order->lastTransaction->parentId : $transaction->order->lastTransaction->id;
            $form->populate($transaction, $this);

            try {
                $response = $form->updateOrder();

                if($response->isSuccessful()) $this->log('Updated authorized order '.$transaction->order->number.' ('.$transaction->order->id.')');
            } catch (\Exception $e) {
                $transaction->note = 'Created Klarna Order';
                $form->populate($transaction, $this);
                $response = $form->createOrder();

                if($response->isSuccessful()) $this->log('Authorized order '.$transaction->order->number.' ('.$transaction->order->id.')');
            }
        }
        else {
            $transaction->note = 'Created Klarna Order';
            $form->populate($transaction, $this);
            $response = $form->createOrder();

            if($response->isSuccessful()) $this->log('Authorized order '.$transaction->order->number.' ('.$transaction->order->id.')');
        }

        return $response;
    }
```

**Comment by jellingsen** [comment]
That is actually a great solution @SandraSundqvist, thank you.

**Comment by jellingsen** [comment]
This is now released. Apologize for the delay and thank you for your help.
