### ISSUE TITLE
Craft Commerce 4 Support

### ISSUE THREAD

**Issue by mark-reactor15** [elleracompany/commerce-klarna-checkout#72]
Is this planned and is there an ETA?

**Comment by jellingsen** [comment]
This is planned, but it is a rather large change so unfortunatly i do not have an ETA at this moment.

**Comment by eddiedale** [comment]
Any updates regarding this?

**Comment by johanneshakonsen** [comment]
^also keen on an update here :)

**Comment by aelvan** [comment]
Is Craft 4 support still planned?

**Comment by tmjoen** [comment]
Any news here? I'd love to see support for this!

**Comment by aarmitage** [comment]
This issue isn't far off being open for 2 years now. Do you think it's realistic there'll be a Craft 4 (or even 5 if we're forward thinking) or should we consider the plugin abandoned?

**Comment by jellingsen** [comment]
Hi everyone.

We no longer have any clients using this plugin in their systems, and the sales are unfortunately not enough to justify spending any significant time on this plugin, and it is therefor now considered abandoned :(

**Comment by aelvan** [comment]
@jellingsen Thanks for clarifying. Could you please mark the plugin as abandoned in the Craft Console? That would make it possible for us to fork it and continue using it without being bugged about renewal fees.

**Comment by engram-design** [comment]
@jellingsen Hey there from [Verbb](https://verbb.io). Just wanted to reach out to see if you'd consider transferring this plugin to us so that we can continue development on it. Considering it's been marked as abandoned now. Let me know!
